apiVersion: 1

contactPoints:
  - orgId: 1
    name: slack-alerts
    type: slack
    settings:
      token: ${SLACK_BOT_TOKEN}
      recipient: "#alerts"
      username: "Grafana Alert"
      icon_emoji: ":warning:"
      title: "{{ .GroupLabels.alertname }} - {{ .Status }}"
      text: |
        {{ range .Alerts }}
        **Alert:** {{ .Annotations.summary }}
        **Description:** {{ .Annotations.description }}
        **Severity:** {{ .Labels.severity }}
        **Value:** {{ .Value }}
        {{ end }}

policies:
  - orgId: 1
    receiver: slack-alerts
    group_by: ['alertname']
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 1h