name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: pgvector/pgvector:pg15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Setup database
      run: |
        npx prisma generate
        npx prisma db push
        npm run db:seed
      env:
        DATABASE_URL: postgresql://test:test@localhost:5432/test

    - name: Run linting
      run: npm run lint

    - name: Run accessibility tests
      run: npm run test:accessibility

    - name: Run build
      run: npm run build
      env:
        DATABASE_URL: postgresql://test:test@localhost:5432/test

    - name: Run load tests
      run: |
        npm run build
        npm start &
        sleep 10
        npx k6 run k6/load-test.js --out json=load-test-results.json
      env:
        DATABASE_URL: postgresql://test:test@localhost:5432/test
        BASE_URL: http://localhost:5000

    - name: Upload load test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: load-test-results
        path: load-test-results.json